import { IAge, IStroke } from "./model";

export const STROKES: IStroke[] = [
	{
		value: "50F",
		label: "50m Freistil",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "100F",
		label: "100m Freistil",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "200F",
		label: "200m Freistil",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "400F",
		label: "400m Freistil",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "800F",
		label: "800m Freistil",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "1500F",
		label: "1500m Freistil",
		scm: true,
		lcm: true,
		master: true,
	},
	{ value: "50B", label: "50m Brust", scm: true, lcm: true, master: true },
	{ value: "100B", label: "100m Brust", scm: true, lcm: true, master: true },
	{ value: "200B", label: "200m Brust", scm: true, lcm: true, master: true },
	{ value: "50R", label: "50m Rücken", scm: true, lcm: true, master: true },
	{
		value: "100R",
		label: "100m Rücken",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "200R",
		label: "200m Rücken",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "50S",
		label: "50m Schmetterling",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "100S",
		label: "100m Schmetterling",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "200S",
		label: "200m Schmetterling",
		scm: true,
		lcm: true,
		master: true,
	},
	{
		value: "100L",
		label: "100m Lagen",
		scm: true,
		lcm: false,
		master: true,
	},
	{ value: "200L", label: "200m Lagen", scm: true, lcm: true, master: true },
	{ value: "400L", label: "400m Lagen", scm: true, lcm: true, master: true },
	{
		value: "4x 50F",
		label: "4x 50m Freistil",
		scm: true,
		lcm: true,
		master: false,
	},
	{
		value: "4x 100F",
		label: "4x 100m Freistil",
		scm: true,
		lcm: true,
		master: false,
	},
	{
		value: "4x 200F",
		label: "4x 200m Freistil",
		scm: true,
		lcm: true,
		master: false,
	},
	{
		value: "4x 50L",
		label: "4x 50m Lagen",
		scm: true,
		lcm: true,
		master: false,
	},
	{
		value: "4x 100L",
		label: "4x 100m Lagen",
		scm: true,
		lcm: true,
		master: false,
	},
];

export const AGES: IAge[] = [
	{ value: "20", label: "AK 20" },
	{ value: "25", label: "AK 25" },
	{ value: "30", label: "AK 30" },
	{ value: "35", label: "AK 35" },
	{ value: "40", label: "AK 40" },
	{ value: "45", label: "AK 45" },
	{ value: "50", label: "AK 50" },
	{ value: "55", label: "AK 55" },
	{ value: "60", label: "AK 60" },
	{ value: "65", label: "AK 65" },
	{ value: "70", label: "AK 70" },
	{ value: "75", label: "AK 75" },
	{ value: "80", label: "AK 80" },
	{ value: "85", label: "AK 85" },
	{ value: "90", label: "AK 90" },
	{ value: "95", label: "AK 95" },
	{ value: "100", label: "AK 100" },
];
